### ISSUE TITLE
Updating to Next 13.2+ with NX 15.9 or 16

### ISSUE THREAD

**Issue by electroheadfx** [endalk200/create-t3-nx#22]
Did you have too the issue with NX ? https://github.com/nrwl/nx/issues/15214

**Comment by endalk200** [comment]
@electroheadfx no I haven't come across that issue. I am working on adding expo app that uses the same backend.

**Comment by endalk200** [comment]
Did had a chance to try it out?

**Comment by electroheadfx** [comment]
No I can't anymore to move Next 13.1.1 to 13.2+ with NX. The update script broke Next. It works onlt on a fresh NX/Next installation.
